### ISSUE TITLE
Migration fails but transaction was successful

### ISSUE THREAD

**Issue by jbunce** [omisego/plasma-contracts#380]
```
[X ] bug report
[ ] feature request
```

```
## Current Behavior
Migration failure from migration on mainnet:

npx truffle migrate --reset --network infura      


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Starting migrations...
======================
> Network name:    'infura'
> Network id:      1
> Block gas limit: 0x963fa9


1_initial_checks_and_migrations.js
==================================
Deployer address: 0x0aCEF3CD1aAaC6eF878d3AEf0f7B55744CcBc215
Authority address: 0x8d45B2644e25dCA038150a48D90FB01EAd7Dd56b
Funding authority address...
Successfully funded authority address.

   Replacing 'Migrations'
   ----------------------
   > transaction hash:    0x1974453caefce6c5b5d340d355aeb8024e9aa6e75cd9ce8ea65f5ac57c71b567
   > Blocks: 4            Seconds: 33
   > contract address:    0x9f9dfc368788bf934848153ac5349657B3C76BCF
   > block number:        8777839
   > block timestamp:     1571577828
   > account:             0x0aCEF3CD1aAaC6eF878d3AEf0f7B55744CcBc215
   > balance:             0.28071145
   > gas used:            190982
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.00381964 ETH


   > Saving migration to chain.
   > Saving artifacts
   -------------------------------------
   > Total cost:          0.00381964 ETH


2_deploy_plasma_framework.js
============================

   Deploying 'PlasmaFramework'
   ---------------------------
   > transaction hash:    0xb5e58ff70508a801191dcfd6d2d5b7791e808487ea4145d347034641162dd7eb
   > Blocks: 3            Seconds: 66
   > contract address:    0x70947B1ef6f639047f35E2CC80D6E7D93afd893E
   > block number:        8777844
   > block timestamp:     1571577917
   > account:             0x8d45B2644e25dCA038150a48D90FB01EAd7Dd56b
   > balance:             0.11230594
   > gas used:            4384703
   > gas price:           20 gwei
   > value sent:          0 ETH
   > total cost:          0.08769406 ETH


Error: Error: Error: insufficient funds for gas * price + value
    at Object.run (/Users/jbunce/plasma-contracts/plasma_framework/node_modules/truffle/build/webpack:/packages/migrate/index.js:96:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.38 (core: 5.0.38)
Node v10.16.3
```

Transaction was succesful: https://etherscan.io/tx/0xb5e58ff70508a801191dcfd6d2d5b7791e808487ea4145d347034641162dd7eb

## Expected Behavior

Migration completes

## Steps to Reproduce

`npx truffle migrate --reset --network infura` on network mainnet branch `integration_949_elixir_omg_pr`

**Comment by jbunce** [comment]
Tracking this in another repo.

**Comment by boolafish** [comment]
@jbunce we can actually transfer issue cross repo now! some amazing GH feature
