### ISSUE TITLE
Gas limit error

### ISSUE THREAD

**Issue by m1cm1c** [omisego/plasma-contracts#497]
I tried this project on a local PoW chain and pre-funded the 3 addresses involved with 100 Ether each. However, upon running `./node_modules/.bin/truffle truffle migrate --network remote`, I get this output despite the gas limit on my chain currently being `2925506206`:

```
Using network 'remote'.


Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.

Deployer address: 0x3a43F087bB52Fd979d9365Be4908b35220fc0842
Maintainer address: 0x9605B4B86cEFf498F0340645beD84d903b710662
Authority address: 0x1a0627d654c251253E736865F25B397De28d041E
maintainer already has 100 ETH, skipping funding.
authority already has 100 ETH, skipping funding.
Deployer contains 100 ETH
Maintainer contains 100 ETH
Authority contains 100 ETH

########################### Notice ############################
It is recommended to have 0.2 ETH in the maintainer and authority address
With 1.0 ETH in the deployer address
Otherwise the deployement might fail
###############################################################

Error: Error: Error: while migrating Migrations: The contract code couldn't be stored, please check your gas limit.
    at Object.run (/some/path/plasma-contracts/plasma_framework/node_modules/truffle/build/webpack:/packages/migrate/index.js:96:1)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.0.38 (core: 5.0.38)
Node v10.17.0
```

## System Specs
I ran this on Manjaro. My Python version is 3.7.4.

```
$ pip freeze
apipkg==1.5
appdirs==1.4.3
astroid==2.3.3
attrdict==2.0.1
attrs==19.3.0
base58==1.0.3
borgbackup==1.1.10
btrfsutil==1.1.1
CacheControl==0.12.5
chardet==3.0.4
colorama==0.4.1
cupshelpers==1.0
cytoolz==0.10.1
distlib==0.2.9
distro==1.4.0
docopt==0.6.2
eip712-structs==1.1.0
entrypoints==0.3
eth-abi==2.0.0
eth-account==0.4.0
eth-hash==0.2.0
eth-keyfile==0.5.1
eth-keys==0.2.4
eth-rlp==0.1.2
eth-tester==0.2.0b2
eth-typing==2.2.1
eth-utils==1.8.1
execnet==1.7.1
flake8==3.7.9
hexbytes==0.2.0
html5lib==1.0.1
idna==2.8
importlib-metadata==0.23
iotop==0.6
ipfshttpclient==0.4.12
isort==4.3.21
Jade-Application-Kit==2.0.9
jsonschema==2.6.0
keyutils==0.6
lazy-object-proxy==1.4.3
lensfun==0.3.2
llfuse==1.3.6
lockfile==0.12.2
louis==3.11.0
lru-dict==1.1.6
mccabe==0.6.1
more-itertools==7.2.0
msgpack==0.6.2
multiaddr==0.0.8
netaddr==0.7.19
npyscreen==4.10.5
packaging==19.2
pacman-mirrors==4.15
parsimonious==0.8.1
pep517==0.6.0
Pillow==6.2.0
-e git+git@github.com:omisego/plasma-contracts.git@500291de975d7f82e21799c9f37797d68f564911#egg=plasma_contracts&subdirectory=plasma_framework/python_tests
pluggy==0.13.1
progress==1.5
protobuf==3.11.0
psutil==5.6.7
pwquality==1.4.2
py==1.8.0
py-solc-simple==0.0.14
py-solc-x==0.4.0
pycairo==1.18.2
pycodestyle==2.5.0
pycryptodome==3.9.4
pycups==1.9.74
pycurl==7.43.0.3
pyflakes==2.1.1
PyGObject==3.34.0
pylint==2.4.4
pyparsing==2.4.4
PyQt5==5.13.2
PyQt5-sip==4.19.19
pysha3==1.0.2
pysmbc==1.0.16
pytest==5.3.1
pytest-cache==1.0
pytest-forked==1.1.3
pytest-xdist==1.30.0
pytest-xprocess==0.12.1
pytoml==0.1.21
PyYAML==5.1.2
reportlab==3.5.32
requests==2.22.0
retrying==1.3.3
rlp==1.1.0
semantic-version==2.8.3
six==1.12.0
team==1.0
toolz==0.10.0
typed-ast==1.4.0
udiskie==1.7.7
urllib3==1.25.6
varint==1.0.2
wcwidth==0.1.7
web3==5.0.0
webencodings==0.5.1
websockets==7.0
wrapt==1.11.2
youtube-dl==2019.10.29
zipp==0.6.0
```

**Comment by boolafish** [comment]
what is the block gas limit of your POW chain? Our contract is actually quite big so require a bit high gas limit (around 6 million)

**Comment by m1cm1c** [comment]
@boolafish It's 2 925 506 206.

**Comment by boolafish** [comment]
@m1cm1c We previously have noticed that Geth would need to take some time to increase the gas limit to the targeting block gas limit. The chain increase the gas kind of on demand.

Our previous issue: https://github.com/omisego/plasma-contracts/issues/199#issuecomment-519806483

Can you check if this is the issue or not?

**Comment by boolafish** [comment]
btw, just realize we need slightly more than 6m of gas not (sigh). However, I think as you are using `remote` so the transaction would be sending around 6.7million of gas by default which should be fine. Just FYI.

(FYI: https://github.com/trufflesuite/truffle/issues/2278)

**Comment by boolafish** [comment]
@m1cm1c is this still an issue on your side?

**Comment by m1cm1c** [comment]
No. Thank you for your support. It was a weird problem. Sorry I forgot to close this issue.
